name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  build:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1.1
      with:
        mono-version: 6.6 
        xamarin-ios-version: 13 
        xamarin-mac-version: latest 
        xamarin-android-version: 10.1.3.7 
        xcode-version: 11.5 

